### ISSUE TITLE
Search Issue

### ISSUE THREAD

**Issue by CristhianSalta** [ekokotov/object-table#10]
I have tried your sample table at http://ekokotov.github.io/object-table/. But, I think it doesn't work very well with Search Filter. Looking for Katheryn (Or just 'Ka') , it shows '9 records' text, but there is no table.

**Comment by ekokotov** [comment]
.io page uses previous version of angular-object-table. This issue is already fixed in current version. I'll update io pages after release.

**Comment by ekokotov** [comment]
Fixed. Check new release please or test described issue at  http://ekokotov.github.io/object-table/ . 
Thank you.
