### ISSUE TITLE
Columns drag-n-drop

### ISSUE THREAD

**Issue by ekokotov** [ekokotov/object-table#11]
Peoples, how about Drag-n-Drop for columns? Should I implement ?

**Comment by vlio20** [comment]
Yes, it would be a very nice feature.

**Comment by ekokotov** [comment]
It's implemented as a beta. Will be included into next release.

**Comment by AhmedAlatawi** [comment]
It seems like the drag-n-drop feature doesn't work in IE 11 browser. Can this be fixed? thanks!
