### ISSUE TITLE
Custom Search based on multiple words

### ISSUE THREAD

**Issue by ajitdixit** [ekokotov/object-table#13]
Can we have search on multiple words  seperated by space
something similar to following function from advanced  angular grid

TestNameFilter.prototype.doesFilterPass = function (node) {
        var filterText = this.$scope.filterText;
        if (!filterText) {
            return true;
        }
        // make sure each word passes separately, ie search for firstname, lastname
        var passed = true;
        filterText.toLowerCase().split(" ").forEach(function(filterWord) {
            if (node.value.toString().toLowerCase().indexOf(filterWord)<0) {
                passed = false;
            }
        });
        return passed;
    };

**Comment by ekokotov** [comment]
Yes. Just describe your filter and add as additional filter (add-filter attribute) like here: 
http://ekokotov.github.io/object-table/samples.html#/additional_filters
