### ISSUE TITLE
Add Column Selection

### ISSUE THREAD

**Issue by fynnfeldpausch** [ekokotov/object-table#15]
Hi there,

is there any way to have a column selector for the table? I was not able to find one at first glance.

Many thanks.

**Comment by ekokotov** [comment]
Hi,
What do you mean by 'column selector for the table' ?

2015-07-06 13:52 GMT+03:00 Fynn Feldpausch <notifications@github.com>:

**Comment by fynnfeldpausch** [comment]
Hi, I mean a functionality to toggle the visibility of table columns...

**Comment by ekokotov** [comment]
There is no built-in functionallity. But you can easy add this one. It is
possible.
Just use custom header pattern and add 'ng-show/ng-hide' or 'ng-class' (is
better) attribute to your headers. if you will have a troubles - provide me
your markup.
thanks

2015-07-06 15:52 GMT+03:00 Fynn Feldpausch <notifications@github.com>:
