### ISSUE TITLE
Duplicate tbody when minified

### ISSUE THREAD

**Issue by langerc** [ekokotov/object-table#16]
hi

i experience a cracy situation - on my development envirenoment everything is fine but if i run it with gulp serve:dist and the minified version is created the tbody is always added twice so the table has twice as many rows as nessessary.

any idea?

**Comment by ekokotov** [comment]
Are u using the last version ? Or last release version?

**Comment by langerc** [comment]
my bower file says 0.1.6
do i have to switch to the github verison without using bower?

**Comment by ekokotov** [comment]
langerc, yes. Try please with the last version. It's interesting behaviour.

**Comment by langerc** [comment]
hi

i tried with the latest version - the tbody element and all its content is added twice after minification with gulp serve-dist

this does not happen if you run with gulp serve - the unminified version

strange but .. true

thank you
christoph

**Comment by ekokotov** [comment]
show me please your HTML markup. I'll try to reproduce this strange thing.

**Comment by ekokotov** [comment]
I tried with the last version (builded using my internal gulp task - run 'gulp build' from main library directory). And everything is fine. Show me your HTML markup and your 'gulp serve-dist' task.

**Comment by langerc** [comment]
im working on it - its not so easy cause the project has several thousand lines - will try to do a plunkr - but this will take some days cause i have to travel to the austrian nationals in skydiving.

this is the code i use in the template, i just copied one of your examples. pendingJournals is an array, source is restangular. Maybe that helps 

<table object-table class="poli"
       data="pendingJournals"
       display="5"
       headers="Customer,Amount,Author"
       fields="lastname,firstname,amount,author"
       sorting="false" search="false"
       paging="true">
    <tbody>
    <tr ng-dblclick="$owner.selectJournal(item);setSelected(item)">
        <td>{{::item.lastname}} {{::item.firstname}}</td>
        <td class="text-right" width="100px">{{::item.amount | number:2}}</td>
        <td  width="150px">{{::item.author}}</td>
    </tr>
    </tbody>
</table>


have a nice day
christoph

**Comment by langerc** [comment]
How to reproduce the Probelm
use this as base, its some simple steps and you get an empty project with everything you need (well most of it)
https://github.com/Swiip/generator-gulp-angular

then add the above table to the main.controller.js below activate

vm.pendingJournals = [{"id":11,"lastname":"firstname","firstname":"lastname","amount":10.0,"author":"web"},
 {"id":12,"lastname":"firstname1","firstname":"lastname1","amount":20.0,"author":"web"}];

add a table with tbody to main.html
  <table object-table class="poli"
         data="main.pendingJournals"
         display="5"
         headers="Customer,Amount,Author"
         fields="lastname, firstname,amount,author"
         sorting="false" search="false"
         paging="true">
    <tbody>
    <tr ng-dblclick="$owner.selectJournal(item);setSelected(item)">
      <td>{{::item.lastname}} {{::item.firstname}}</td>
      <td class="text-right" width="100px">{{::item.amount | number:2}}</td>
      <td  width="150px">{{::item.author}}</td>
    </tr>
    </tbody>
  </table>

run gulp serve:dist

you will see 4 lines instead of 2. if you run gulp serve - everything is fine.

**Comment by ekokotov** [comment]
It's crazy. I can't reproduce your issue.
![image](https://cloud.githubusercontent.com/assets/11966000/9227099/bac19a46-40c6-11e5-9569-d54416608871.png)
and run "gulp serve:dist"
result is:
![image](https://cloud.githubusercontent.com/assets/11966000/9227120/d592f388-40c6-11e5-8b40-7d7c893d40f6.png)

P.S. I've installed angular-object-table using bower. @version v0.1.8

**Comment by langerc** [comment]
well i tried 0.1.8 and 0.1.9

never mind i will replace the table module with another one since i cant spend more time on that issue .. 

but you did not use the full framework you wrote your own html - i think it has something to do with the templating and minimzing of them.

if you dont mind try to fill in the structure i sent you in the main.html template without adding a body - it will use the ui-router template and all the stuff then,

have a nice day
christoph

**Comment by ekokotov** [comment]
I've used your structure:
- generator-gulp-angular
+ bower install angular-object-table
Ok. Will try generator-gulp-angular with UI-Routing mode
