### ISSUE TITLE
Can't edit empty data

### ISSUE THREAD

**Issue by lucasBertola** [ekokotov/object-table#17]
By exemple  on http://ekokotov.github.io/object-table/?utm_source=angular-js.in&utm_medium=website&utm_campaign=content-curation

If I clear a data (like "Liz") , I can't edit this data later.
Same if the data was empty from the beginning .

Thx

**Comment by ekokotov** [comment]
I can't reproduce this bug in Chrome. What browser are u using ? I can clear all data inside call and add new value later.

**Comment by lucasBertola** [comment]
Indeed, this bug can't be reproduced in chrome.
But this bug is on last firefox.

**Comment by ekokotov** [comment]
Ok. fixed this thing in new release. Please update library to 0.2.1.
