### ISSUE TITLE
automated build depending on bower does not include files

### ISSUE THREAD

**Issue by langerc** [ekokotov/object-table#2]
the selected main index.js does not exist

changing it to
  "main": ["build/object-table_v0.1.3.js",
  "build/object-table-style.css"
  ],

incudes the correct files in a gulp build (or any build depending on bowers gulp module)

**Comment by ekokotov** [comment]
Changed. Check it please. Should I include for convenience
"build" directory to repository?

**Comment by langerc** [comment]
I dont think its possible to include a directory there - i checked about 30 bower dependencies im using - all of them include the files with the filenames, many of them (about 50%) dont use the version in the filename inside the dist directory. 
Since modules will be minified/concatenated there should not be a problem with caching or something like that.

**Comment by ekokotov** [comment]
I agree. It's a good idea. I'll remove version from file name and will add as a comment in compressed file.
