### ISSUE TITLE
For a custom row or header is it possible to access functions and variables on the parent scope?

### ISSUE THREAD

**Issue by ashleydavis** [ekokotov/object-table#20]
For example... the formatName function call in the following example is defined on a parent scope.

I can't seem to get this to work.

    <table  object-table 
            from-url="http://beta.json-generator.com/api/json/get/DXXROxj" 
            data="exportDataVariable" 
            display="10" 
            headers="Name, Eye color, Age,Balance,Company,Home address,Favorite Fruit" 
            fields="name,eyeColor,age,balance,company,address,favoriteFruit" 
            sorting="compound">
        <tbody>
            <tr>
                <td>{{formatName(item.name)}}</td>
                <td><div class="{{::item.eyeColor}} eye"></div>
                    {{::item.eyeColor}}
                </td>
                <td>{{::item.age}}</td>
                <td style="background-color:rgb(212, 255, 227)">{{::item.balance}}</td>
                <td>{{::item.company}}</td>
                <td>{{::item.address}}</td>
                <td>{{::item.favoriteFruit}}</td>
            </tr>
        </tbody>
    </table>

**Comment by ashleydavis** [comment]
You might need to make use of ng-transclude in your directive template to solve this problem.

https://docs.angularjs.org/api/ng/directive/ngTransclude

**Comment by ekokotov** [comment]
Its possible.
like:
$owner. formatName()
$owner - is a link of your controller

http://ekokotov.github.io/object-table/samples.html#/custom_rows_headers

**Comment by ekokotov** [comment]
Hi. If formatName is your controller function - just use '$owner.formatName'
like I described here:
http://ekokotov.github.io/object-table/samples.html#/custom_rows_headers
Sorry for delay.

2015-10-13 22:35 GMT-07:00 Ashley Davis <notifications@github.com>:
