### ISSUE TITLE
Can't copy example code

### ISSUE THREAD

**Issue by ashleydavis** [ekokotov/object-table#21]
Your examples are great, but they can't be copied and pasted!

It would be much easier to get started with object-table if it were possible to copy and paste the example code.

http://ekokotov.github.io/object-table/samples.html#/basic

![screenshot_1](https://cloud.githubusercontent.com/assets/625126/10603734/11156878-7763-11e5-8a25-4fb2de3a3850.png)

**Comment by ekokotov** [comment]
Oh. Sorry. Good idea. Will fix it

**Comment by ekokotov** [comment]
Thanks
