### ISSUE TITLE
Dynamic headers

### ISSUE THREAD

**Issue by hnguyenec** [ekokotov/object-table#22]
Is there anyway to render dynamic headers (ie: headers = "{{vm.headers}}" )

**Comment by ekokotov** [comment]
Like u described, no. But you can use custom header template. (http://ekokotov.github.io/object-table/samples.html#/custom_headers)[example]

**Comment by Parthvora** [comment]
@ekokotov , is there anyway that I can use custom header as well as column dragging too? Use of custom header stops column drag. All I want to do is to call an function on each <th>, but as soon as put that custom header HTML, column dragging stops working.

**Comment by ekokotov** [comment]
I will implement this
