### ISSUE TITLE
Uncaught TypeError

### ISSUE THREAD

**Issue by HashirHussain** [ekokotov/object-table#23]
Getting error on drag and drop columns.

Uncaught TypeError: Cannot read property 'setData' of undefined
Uncaught TypeError: Cannot read property 'getData' of undefined

**Comment by ekokotov** [comment]
could you please provide me your markup and browser version?

**Comment by Comi89** [comment]
+1
When remove jQuery from project it's work, but i need jQuery in project.
i install table with bower install --save angular-object-table
Thank you...

**Comment by Parthvora** [comment]
yup, @Comi89 is right, when using this plugin with jQuery it gives:
Uncaught TypeError: Cannot read property 'setData' of undefined
Uncaught TypeError: Cannot read property 'getData' of undefined

anyway to solve it even if jQuery is there?

**Comment by Comi89** [comment]
i solve this problem on this way:
i set e.dataTransfer.setData.... to e.originalEvent.dataTransfer.setData in object-table.js - key is in originalEvent method... Also do that for getData...

Also do that in angular directive in bower components for columns reorder.

it works for me without problems, i hope that i help...
Cheers :)

**Comment by Parthvora** [comment]
Thanks a lot Comi89, it worked like a charm. :+1:

**Comment by ekokotov** [comment]
Thanks guys. Will add this fix to release soon

**Comment by ekokotov** [comment]
Can't reproduce your issue. What version of Jquery are you used?

**Comment by Parthvora** [comment]
@ekokotov its v2.1.4

**Comment by ekokotov** [comment]
update to new version

**Comment by Parthvora** [comment]
Hey @ekokotov 

sorry mate but its still not working with even latest version of jQuery
Here is plunker for that:

https://plnkr.co/edit/sTeX2Kj69S7vp5cZqrEX?p=preview

Keep your console open and try to move the columns by dragging then and you will get those errors.

**Comment by ekokotov** [comment]
Just update object-table to 0.2.2 (is available).
See result:
https://plnkr.co/edit/Ss7auwzwjiKyu7DHkOjz?p=preview
