### ISSUE TITLE
Plugin not working with jquery

### ISSUE THREAD

**Issue by cvile** [ekokotov/object-table#26]
Greetings, i struggle to implement drag n drop feature (with resize) on columns. I have noticed that if i remove jquery (which is referenced above angular.js dependency) plugin does work, if i try to reorder columns with jquery included, an error occurs. 

Uncaught TypeError: Cannot read property 'setData' of undefined  in object-table.js on line 7. The same for getData function.

Another problem i have noticed, even if i remove jquery from index and reorder works (on latest chrome, firefox and safari) resizing of columns not working in chrome (without errors) but still works in safari and firefox. Dont have idea why so.

**Comment by cvile** [comment]
It seems when you change in draggableDirective.js e.dataTransfer.setData ... to e.originalEvent.dataTransfer.setData (also in object-table.js) everything seems to work again xD

Btw i have noticed that reordering columns (drag n drop) not working on mobile devices via browser. Do you have any idea why? tnx in advance...

Best regards.

**Comment by ekokotov** [comment]
Because here is no touch events for mobile devices. May be enable drag-n-drop by long touch... something like this. According this issue... I will test it with jquery to find a problem. Thanks for you comment.

**Comment by ekokotov** [comment]
Please try to update to new version. Should be fixed. + added on-edit event.
