### ISSUE TITLE
Trigger a function after updating model

### ISSUE THREAD

**Issue by OpsRJ** [ekokotov/object-table#27]
I would like to have a possibility to trigger a function after model updating. Would be nice to have it.

**Comment by ekokotov** [comment]
Do you need something like:
`<table object-table class="hover-column" data="data" headers="Age, full Name" fields="age,name" sorting="compound" editable="true" on-edit="logChange($oldValue, $newValue)" search="separate" resize="true" drag-columns="true"></table>`
?

**Comment by ekokotov** [comment]
on-edit="logChange($oldValue, $newValue)"

**Comment by OpsRJ** [comment]
Yes or just a possibility to call a custom function.

**Comment by ekokotov** [comment]
Implemented. Please visit [samples](http://ekokotov.github.io/object-table/samples.html#/editable_cells) to details. Let me know if you will have any question.

**Comment by ekokotov** [comment]
update to new version

**Comment by OpsRJ** [comment]
Thank you very much :)
