### ISSUE TITLE
Put ngClick on all <th> in table header 

### ISSUE THREAD

**Issue by Parthvora** [ekokotov/object-table#29]
Hello,

I want to Put ngClick on all the < th > tags in table header, but with below syntax how that is going to be possible?

< table object-table from-url="http://some-url.com/getData" data="exportDataVariable" display="2" 
       headers="Name, Age" fields="name, age" sorting="false" editable="true"></table>

Actually what I want to do is to put my custom server side sorting there instead of plugin's built in client side sorting.

This plugin is really good when there is limited data in table, but however in real life big project where there is millions of data to display in table, its not good to use it because it gets whole data in a single shot and based on that it gives sorting. 

Any help would be appreciated. 
Thanks

**Comment by ekokotov** [comment]
It's possible to use custom header/row pattern. Look please on this example:
http://ekokotov.github.io/object-table/samples.html#/custom_rows_headers

**Comment by Parthvora** [comment]
Thanks @ekokotov , yes using custom header, we can get ngClick working, but I also want draggable columns which is not working with custom headers. So I can get either of one thing. So is there anyway I can get both the things together?

**Comment by ekokotov** [comment]
http://ekokotov.github.io/object-table/samples.html#/draggable_headers

If you are using custom templates:

add allow-drag attribute to draggable header
суббота, 23 января 2016 г. пользователь Parthvora написал:
