### ISSUE TITLE
angular 2 and maintainance

### ISSUE THREAD

**Issue by ehsaanwelcome** [ekokotov/object-table#36]
Hi Evgeny Kokotov,
i really like your efforts in angular object table, i wanna switch to this library.
i want to know future plans for angular 2, do you have plan to maintain this library in long run?
Thanks

**Comment by ekokotov** [comment]
Hi Muhammad. Thank you for feedback. It’s good question. I think I will create new version based on angular 2 from scratch. But you know syntax and other things are so different between angular 1.x and angular 2.0 , it will be like new library.
