### ISSUE TITLE
ng-click invalid ?

### ISSUE THREAD

**Issue by liaohui1080** [ekokotov/object-table#37]
`<td >{{$index}}{{::item.name}}</td>
				<td >{{::item.age}}</td>
				<td >
				{{::item.money}}
				</td>
				<td>  <button ng-click="dianji()">fsdf</button></td>`

Can not run normally??

**Comment by liaohui1080** [comment]
sorry  我自己找到了 $owner.dianji()

**Comment by ekokotov** [comment]
is `dianji()` is controller method of view ? try use controller as vm for your controller and vm.dianji() in your template.
