### ISSUE TITLE
bower.json exports non-existent file, breaks wiredep

### ISSUE THREAD

**Issue by knksmith57** [ekokotov/object-table#4]
`bower.json` currently references `build/object-table_v0.1.4.js`, which does not exist.

It should, instead, reference `build/object-table.js`.

This bug breaks wiredep and other tools that attempt to autoload bower packages via the `main` field which is [meant to specify](http://bower.io/docs/creating-packages/#bowerjson):

> The primary acting files necessary to use your package.

**Comment by ekokotov** [comment]
fixed. Thank you!
