### ISSUE TITLE
Dynamic headers and fields from scope variable

### ISSUE THREAD

**Issue by ahoset** [ekokotov/object-table#46]
``` html
<table object-table 
       data="exportDataVariable" 
       display="2" 
       headers="Name, Age" 
       fields="name, age"
       sorting="false"
       editable="true" 
></table>
```

How do i pass a variable to headers, and fields like the done for data property ?
The normal {{headers}} for $scope.headers does not work.

From the controller

``` javascript
$scope.headers = "Name, Age";
```

Can you help with this?

Best regards, Alexander Hoset

**Comment by ekokotov** [comment]
it should work like on your example. sorry for delay.
