### ISSUE TITLE
publish hotfix for changes to bower

### ISSUE THREAD

**Issue by knksmith57** [ekokotov/object-table#6]
#4 + #5 now make the bower export work properly, but they currently require developers to use hackish commitish format in their `bower.json` files. Please publish the fixed changes so we can go back to using good old `bower install angular-object-table`.

**Comment by knksmith57** [comment]
In the meantime, here's the syntax devs will need to use in their `bower.json` files:

```json
{
  "dependencies": {
    "angular-object-table": "ekokotov/object-table#44e6a01"
  }
} 
```

**Comment by ekokotov** [comment]
Fixed in v.0.1.6 . Thank you a lot!
