### ISSUE TITLE
when search parameter change, is it more suitable to reset the page to first page?

### ISSUE THREAD

**Issue by jinceon** [ekokotov/object-table#9]
when search parameter change, is it more suitable to reset the page to first page?
for example,initially there are 50 records.

bug repeat steps:
1. change page to the last page ,eg pagesize 10, the last page is 5. 
2. type some character in filter,now result records remains 7.  

expect result:
reset page to first page.

actual result:
it still stay in page 5. and pagination bar is invisile

**Comment by ekokotov** [comment]
Hello. 
It is fixed. Please download last version and rebuild. I'll add this fix in next release.
Thank you.
